# Generated by Django 5.2.17 on 2026-08-25 22:00

import apps.contas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[apps.contas.validators.valida_cpf], verbose_name='CPF')),
                ('papel', models.CharField(choices=[('COORDENADOR', 'Coordenador'), ('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno')], max_length=20, verbose_name='papel')),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='matricula')),
                ('siape', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='SIAPE')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acessa o admin')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['nome_completo'],
            },
        ),
    ]
