# Generated by Django 5.2.17 on 2026-08-31 04:13

import apps.contas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alter_usuario_options_alter_usuario_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[apps.contas.validators.valida_cpf], verbose_name='CPF'),
        ),
    ]
