# Generated by Django 5.2.17 on 2026-08-31 04:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_telefone_e_cpf_opcional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('expira_em', models.DateTimeField(verbose_name='expira em')),
                ('usado_em', models.DateTimeField(blank=True, null=True, verbose_name='usado em')),
                ('cancelado_em', models.DateTimeField(blank=True, null=True, verbose_name='cancelado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convites_enviados', to=settings.AUTH_USER_MODEL, verbose_name='convidado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to=settings.AUTH_USER_MODEL, verbose_name='aluno')),
            ],
            options={
                'verbose_name': 'convite de aluno',
                'verbose_name_plural': 'convites de aluno',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['token'], name='contas_conv_token_3e75dd_idx')],
            },
        ),
    ]
