# Generated by Django 5.2.17 on 2026-09-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_convite_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaDeLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP de origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'tentativa de login',
                'verbose_name_plural': 'tentativas de login',
                'indexes': [models.Index(fields=['ip', 'criado_em'], name='contas_tent_ip_92c90b_idx')],
            },
        ),
    ]
