# Generated by Django 5.2.17 on 2026-09-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_tentativadelogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=150, verbose_name='nome completo'),
        ),
    ]
