# Generated by Django 5.2.17 on 2026-09-28 21:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_alter_usuario_nome_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaDeRedefinicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP de origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'tentativa de redefinição',
                'verbose_name_plural': 'tentativas de redefinição',
                'indexes': [models.Index(fields=['ip', 'criado_em'], name='contas_tent_ip_5de4c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='RedefinicaoDeSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('expira_em', models.DateTimeField(verbose_name='expira em')),
                ('usado_em', models.DateTimeField(blank=True, null=True, verbose_name='usado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redefinicoes_de_senha', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'redefinição de senha',
                'verbose_name_plural': 'redefinições de senha',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['token'], name='contas_rede_token_7f3841_idx')],
            },
        ),
    ]
