# Generated by Django 5.2.17 on 2026-08-27 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0008_busca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome do solicitante')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('instituicao', models.CharField(blank=True, max_length=150, verbose_name='instituição')),
                ('num_participantes', models.PositiveSmallIntegerField(verbose_name='participantes previstos')),
                ('periodo_pretendido', models.CharField(blank=True, max_length=100, verbose_name='período pretendido')),
                ('mensagem', models.TextField(blank=True, max_length=2000, verbose_name='mensagem')),
                ('status', models.CharField(choices=[('RECEBIDA', 'Recebida'), ('EM_ANALISE', 'Em análise'), ('ACEITA', 'Aceita'), ('RECUSADA', 'Recusada')], default='RECEBIDA', max_length=20, verbose_name='situação')),
                ('resposta', models.TextField(blank=True, verbose_name='resposta')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='cursos.curso', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'solicitação',
                'verbose_name_plural': 'solicitações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
