# Generated by Django 5.2.17 on 2026-09-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugestaoDeCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome de quem sugere')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('instituicao', models.CharField(max_length=150, verbose_name='instituição')),
                ('tem_laboratorio', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NAO_SEI', 'Não sei informar')], max_length=10, verbose_name='laboratório de informática')),
                ('publico_alvo', models.CharField(max_length=200, verbose_name='público-alvo')),
                ('demanda', models.TextField(max_length=2000, verbose_name='demanda')),
                ('status', models.CharField(choices=[('RECEBIDA', 'Recebida'), ('EM_ANALISE', 'Em análise'), ('ACEITA', 'Aceita'), ('RECUSADA', 'Recusada')], default='RECEBIDA', max_length=20, verbose_name='situação')),
                ('resposta', models.TextField(blank=True, verbose_name='resposta')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'sugestão de curso',
                'verbose_name_plural': 'sugestões de curso',
                'ordering': ['-criado_em'],
            },
        ),
    ]
