# Generated by Django 5.2.17 on 2026-08-27 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('cursos', '0008_busca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='início')),
                ('data_fim', models.DateField(verbose_name='fim')),
                ('local', models.CharField(max_length=200, verbose_name='local')),
                ('vagas', models.PositiveSmallIntegerField(verbose_name='vagas')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20, verbose_name='situação')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='cursos.curso', verbose_name='curso')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to=settings.AUTH_USER_MODEL, verbose_name='professor')),
                ('solicitacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turma', to='catalogo.solicitacao', verbose_name='solicitação de origem')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='turmas.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'participante',
                'verbose_name_plural': 'participantes',
                'ordering': ['nome'],
            },
        ),
    ]
