# Generated by Django 5.2.17 on 2026-08-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254, verbose_name='destinatário')),
                ('assunto', models.CharField(max_length=200, verbose_name='assunto')),
                ('corpo', models.TextField(verbose_name='corpo')),
                ('evento', models.CharField(max_length=50, verbose_name='evento')),
                ('tentativas', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('ultimo_erro', models.TextField(blank=True, verbose_name='último erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['criado_em'],
                'indexes': [models.Index(fields=['enviado_em', 'tentativas'], name='notificacoe_enviado_136c07_idx')],
            },
        ),
    ]
