# Generated by Django 5.2.17 on 2026-08-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='proxima_tentativa_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='próxima tentativa em'),
        ),
    ]
