# Generated by Django 5.2.17 on 2026-08-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex.: 2026/2', max_length=10, unique=True, verbose_name='codigo')),
                ('descricao', models.CharField(max_length=200, verbose_name='descricao')),
                ('data_inicio', models.DateField(verbose_name='inicio')),
                ('data_fim', models.DateField(verbose_name='fim')),
                ('ativa', models.BooleanField(default=False, verbose_name='edicao corrente')),
            ],
            options={
                'verbose_name': 'edicao',
                'verbose_name_plural': 'edicoes',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
