# Generated by Django 5.2.17 on 2026-08-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edicoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edicao',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'edição', 'verbose_name_plural': 'edições'},
        ),
        migrations.AlterField(
            model_name='edicao',
            name='ativa',
            field=models.BooleanField(default=False, verbose_name='edição corrente'),
        ),
        migrations.AlterField(
            model_name='edicao',
            name='codigo',
            field=models.CharField(help_text='Ex.: 2026/2', max_length=10, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='edicao',
            name='data_inicio',
            field=models.DateField(verbose_name='início'),
        ),
        migrations.AlterField(
            model_name='edicao',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='descrição'),
        ),
    ]
