# Generated by Django 5.2.17 on 2026-08-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edicoes', '0002_alter_edicao_options_alter_edicao_ativa_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='edicao',
            constraint=models.UniqueConstraint(condition=models.Q(('ativa', True)), fields=('ativa',), name='apenas_uma_edicao_ativa'),
        ),
    ]
