# Generated by Django 5.2.17 on 2026-08-26 12:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('edicoes', '0003_edicao_apenas_uma_edicao_ativa'),
        ('referenciais', '0003_alter_competencia_options_alter_competencia_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('resumo', models.TextField(verbose_name='resumo')),
                ('tipo_publico', models.CharField(choices=[('ESCOLAR', 'Etapa escolar'), ('COMUNITARIO', 'Público da comunidade')], max_length=20, verbose_name='tipo de público')),
                ('etapa_ano', models.CharField(blank=True, choices=[('EI', 'Educação Infantil'), ('EF01', '1º ano do Ensino Fundamental'), ('EF02', '2º ano do Ensino Fundamental'), ('EF03', '3º ano do Ensino Fundamental'), ('EF04', '4º ano do Ensino Fundamental'), ('EF05', '5º ano do Ensino Fundamental'), ('EF06', '6º ano do Ensino Fundamental'), ('EF07', '7º ano do Ensino Fundamental'), ('EF08', '8º ano do Ensino Fundamental'), ('EF09', '9º ano do Ensino Fundamental'), ('EM01', '1º ano do Ensino Médio'), ('EM02', '2º ano do Ensino Médio'), ('EM03', '3º ano do Ensino Médio')], max_length=4, verbose_name='etapa ou ano escolar')),
                ('publico_descricao', models.CharField(blank=True, max_length=200, verbose_name='descrição do público')),
                ('carga_horaria', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='carga horária (horas)')),
                ('formato', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('HIBRIDO', 'Híbrido'), ('ONLINE', 'Online')], max_length=20, verbose_name='formato')),
                ('pre_requisitos', models.TextField(blank=True, verbose_name='pré-requisitos')),
                ('palavras_chave', models.CharField(blank=True, max_length=300, verbose_name='palavras-chave')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_PRODUCAO', 'Em produção'), ('AGUARDANDO_COORDENADOR', 'Aguardando coordenador'), ('DEVOLVIDO', 'Devolvido pelo coordenador'), ('PUBLICADO', 'Publicado'), ('DESPUBLICADO', 'Despublicado'), ('SUBSTITUIDO', 'Substituído por nova versão')], default='RASCUNHO', max_length=30, verbose_name='situação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('publicado_em', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('competencias', models.ManyToManyField(blank=True, related_name='cursos', to='referenciais.competencia', verbose_name='competências')),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='edicoes.edicao', verbose_name='edição')),
                ('professor_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos_como_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='professor responsável')),
                ('referencial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='referenciais.referencial', verbose_name='referencial pedagógico')),
                ('temas', models.ManyToManyField(blank=True, related_name='cursos', to='cursos.tema', verbose_name='temas')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
