# Generated by Django 5.2.17 on 2026-08-26 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicionado_em', models.DateTimeField(auto_now_add=True, verbose_name='adicionado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to=settings.AUTH_USER_MODEL, verbose_name='aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='cursos.curso', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'membro da equipe',
                'verbose_name_plural': 'membros da equipe',
                'ordering': ['aluno__nome_completo'],
                'constraints': [models.UniqueConstraint(fields=('curso', 'aluno'), name='membro_unico_por_curso')],
            },
        ),
    ]
