# Generated by Django 5.2.17 on 2026-08-26 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_membroequipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PLANO_ENSINO', 'A - Plano de Ensino e Mapeamento Pedagógico'), ('CARDS', 'B - Infográficos e Cards Educativos'), ('CADERNO', 'C - Caderno de Exercícios e Atividades Práticas'), ('VIDEOS', 'D - Vídeo-Aulas'), ('SLIDES', 'E - Slides e Apresentações')], max_length=20, verbose_name='tipo')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_REVISAO', 'Em revisão'), ('APROVADO', 'Aprovado'), ('DEVOLVIDO', 'Devolvido')], default='RASCUNHO', max_length=20, verbose_name='situação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregaveis', to='cursos.curso', verbose_name='curso')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregaveis_sob_responsabilidade', to=settings.AUTH_USER_MODEL, verbose_name='aluno responsável')),
            ],
            options={
                'verbose_name': 'entregável',
                'verbose_name_plural': 'entregáveis',
                'ordering': ['curso', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('conteudo', models.TextField(blank=True, verbose_name='conteúdo')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secoes_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('entregavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='cursos.entregavel', verbose_name='entregável')),
            ],
            options={
                'verbose_name': 'seção',
                'verbose_name_plural': 'seções',
                'ordering': ['entregavel', 'ordem', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='entregavel',
            constraint=models.UniqueConstraint(fields=('curso', 'tipo'), name='entregavel_unico_por_curso'),
        ),
    ]
