# Generated by Django 5.2.17 on 2026-08-26 12:34

import apps.cursos.models.anexo
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_entregavel_secao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador')),
                ('arquivo', models.FileField(max_length=255, upload_to=apps.cursos.models.anexo.caminho_do_arquivo, verbose_name='arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='nome original')),
                ('tamanho', models.PositiveBigIntegerField(verbose_name='tamanho em bytes')),
                ('mime', models.CharField(max_length=100, verbose_name='tipo')),
                ('hash_conteudo', models.CharField(max_length=64, verbose_name='hash do conteúdo')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivos_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'arquivo',
                'verbose_name_plural': 'arquivos',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_midia', models.CharField(choices=[('ARQUIVO', 'Arquivo'), ('VIDEO', 'Vídeo'), ('LINK', 'Link externo')], max_length=20, verbose_name='tipo')),
                ('url', models.URLField(blank=True, verbose_name='link')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('referencia_bibliografica', models.TextField(blank=True, verbose_name='referência bibliográfica')),
                ('rotulo', models.CharField(choices=[('NENHUM', 'Sem rótulo'), ('SEM_GABARITO', 'Versão sem gabarito'), ('COM_GABARITO', 'Versão com gabarito')], default='NENHUM', max_length=20, verbose_name='rótulo')),
                ('tipo_pratica', models.CharField(choices=[('NENHUM', 'Não se aplica'), ('PLUGADA', 'Atividade plugada'), ('DESPLUGADA', 'Atividade desplugada'), ('AMBAS', 'Plugada e desplugada')], default='NENHUM', max_length=20, verbose_name='tipo de prática')),
                ('duracao_minutos', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='duração em minutos')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('entregavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='cursos.entregavel', verbose_name='entregável')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos_enviados', to=settings.AUTH_USER_MODEL)),
                ('secao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos', to='cursos.secao', verbose_name='seção')),
                ('arquivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='cursos.arquivo')),
            ],
            options={
                'verbose_name': 'anexo',
                'verbose_name_plural': 'anexos',
                'ordering': ['entregavel', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='arquivo',
            index=models.Index(fields=['hash_conteudo'], name='cursos_arqu_hash_co_b80258_idx'),
        ),
    ]
