# Generated by Django 5.2.17 on 2026-08-26 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_arquivo_anexo_arquivo_cursos_arqu_hash_co_b80258_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisao', models.CharField(choices=[('APROVADO', 'Aprovado'), ('DEVOLVIDO', 'Devolvido')], max_length=20, verbose_name='decisão')),
                ('comentario', models.TextField(blank=True, verbose_name='comentário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('entregavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='cursos.entregavel', verbose_name='entregável')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisoes', to=settings.AUTH_USER_MODEL, verbose_name='revisor')),
            ],
            options={
                'verbose_name': 'revisão',
                'verbose_name_plural': 'revisões',
                'ordering': ['criado_em'],
            },
        ),
    ]
