# Generated by Django 5.2.17 on 2026-08-26 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_revisao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTransicaoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_PRODUCAO', 'Em produção'), ('AGUARDANDO_COORDENADOR', 'Aguardando coordenador'), ('DEVOLVIDO', 'Devolvido pelo coordenador'), ('PUBLICADO', 'Publicado'), ('DESPUBLICADO', 'Despublicado'), ('SUBSTITUIDO', 'Substituído por nova versão')], max_length=30, verbose_name='de')),
                ('para_status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_PRODUCAO', 'Em produção'), ('AGUARDANDO_COORDENADOR', 'Aguardando coordenador'), ('DEVOLVIDO', 'Devolvido pelo coordenador'), ('PUBLICADO', 'Publicado'), ('DESPUBLICADO', 'Despublicado'), ('SUBSTITUIDO', 'Substituído por nova versão')], max_length=30, verbose_name='para')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicoes', to='cursos.curso', verbose_name='curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transicoes_de_curso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transição de curso',
                'verbose_name_plural': 'transições de curso',
                'ordering': ['criado_em'],
            },
        ),
    ]
