# Generated by Django 5.2.17 on 2026-08-27 03:32

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.functions.comparison
from django.conf import settings
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_logtransicaocurso'),
        ('edicoes', '0003_edicao_apenas_uma_edicao_ativa'),
        ('referenciais', '0003_alter_competencia_options_alter_competencia_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # R62: o dicionario 'portuguese' e sensivel a acento
        # (to_tsvector('portuguese','Robótica') não bate com
        # plainto_tsquery('portuguese','robotica')), e as pessoas digitam sem
        # acento. unaccent() sozinho não serve porque é STABLE, não IMMUTABLE, e
        # não pode entrar numa coluna gerada nem num índice de expressão; por
        # isso a config abaixo copia 'portuguese' e passa o mapeamento por
        # unaccent antes do stemmer, o que se mantém IMMUTABLE. Precisa vir antes
        # dos AddField abaixo: a coluna gerada referencia a config por nome e o
        # Postgres exige que ela já exista.
        CreateExtension("unaccent"),
        migrations.RunSQL(
            sql=(
                "CREATE TEXT SEARCH CONFIGURATION portugues_unaccent (COPY = portuguese);\n"
                "ALTER TEXT SEARCH CONFIGURATION portugues_unaccent\n"
                "  ALTER MAPPING FOR hword, hword_part, word WITH unaccent, portuguese_stem;"
            ),
            reverse_sql="DROP TEXT SEARCH CONFIGURATION IF EXISTS portugues_unaccent;",
        ),
        migrations.AddField(
            model_name='curso',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector(django.db.models.functions.comparison.Coalesce(models.F('titulo'), models.Value(''), output_field=models.TextField()), django.db.models.functions.comparison.Coalesce(models.F('resumo'), models.Value(''), output_field=models.TextField()), django.db.models.functions.comparison.Coalesce(models.F('palavras_chave'), models.Value(''), output_field=models.TextField()), config='portugues_unaccent'), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AddField(
            model_name='curso',
            name='vetor_temas',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True, verbose_name='vetor dos temas'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='curso_busca_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vetor_temas'], name='curso_busca_temas_idx'),
        ),
    ]
