# Generated by Django 5.2.17 on 2026-08-27 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_busca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadEmAndamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_original', models.CharField(max_length=255, verbose_name='nome original')),
                ('tamanho_total', models.PositiveBigIntegerField(verbose_name='tamanho total declarado')),
                ('tamanho_recebido', models.PositiveBigIntegerField(default=0, verbose_name='recebido')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('entregavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='cursos.entregavel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'upload em andamento',
                'verbose_name_plural': 'uploads em andamento',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
