# Generated by Django 5.2.17 on 2026-08-28 01:28

import django.db.models.deletion
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_uploademandamento'),
        ('edicoes', '0003_edicao_apenas_uma_edicao_ativa'),
        ('referenciais', '0003_alter_competencia_options_alter_competencia_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='motivo_versao',
            field=models.TextField(blank=True, verbose_name='motivo desta versão'),
        ),
        migrations.AddField(
            model_name='curso',
            name='raiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versoes', to='cursos.curso', verbose_name='primeira versão desta linhagem'),
        ),
        migrations.AddField(
            model_name='curso',
            name='versao',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='versão'),
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Coalesce(models.F('raiz_id'), models.F('id')), condition=models.Q(('status', 'PUBLICADO')), name='uma_versao_publicada_por_linhagem'),
        ),
    ]
