# Generated by Django 5.2.17 on 2026-08-30 22:15

import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_versoes'),
        ('edicoes', '0003_edicao_apenas_uma_edicao_ativa'),
        ('referenciais', '0003_alter_competencia_options_alter_competencia_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Coalesce(models.F('raiz_id'), models.F('id')), models.F('versao'), name='uma_numeracao_por_linhagem'),
        ),
    ]
