# Generated by Django 5.2.17 on 2026-08-31 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_responsavel_na_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='carga horária (horas)'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='formato',
            field=models.CharField(blank=True, choices=[('PRESENCIAL', 'Presencial'), ('HIBRIDO', 'Híbrido'), ('ONLINE', 'Online')], max_length=20, verbose_name='formato'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='resumo',
            field=models.TextField(blank=True, verbose_name='resumo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipo_publico',
            field=models.CharField(blank=True, choices=[('ESCOLAR', 'Etapa escolar'), ('COMUNITARIO', 'Público da comunidade')], max_length=20, verbose_name='tipo de público'),
        ),
    ]
