# Generated by Django 5.2.17 on 2026-09-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_ficha_opcional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregavel',
            name='tipo',
            field=models.CharField(choices=[('PLANO_ENSINO', '1 - Plano de Ensino e Mapeamento Pedagógico'), ('SLIDES', '2 - Slides e Apresentações'), ('VIDEOS', '3 - Vídeo-Aulas'), ('CARDS', '4 - Infográficos e Cards Educativos'), ('CADERNO', '5 - Caderno de Exercícios e Atividades Práticas'), ('AVALIACAO', '6 - Avaliação')], max_length=20, verbose_name='tipo'),
        ),
    ]
