# Generated by Django 5.2.17 on 2026-09-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_entregavel_sem_devolvido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregavel',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_REVISAO', 'Em revisão'), ('APROVADO', 'Aprovado')], default='RASCUNHO', max_length=20, verbose_name='situação'),
        ),
        migrations.AlterField(
            model_name='revisao',
            name='decisao',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('DEVOLVIDO', 'Devolvido'), ('REABERTO', 'Reaberto')], max_length=20, verbose_name='decisão'),
        ),
    ]
