# Generated by Django 5.2.17 on 2026-09-03 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0018_alter_entregavel_status_alter_revisao_decisao'),
        ('edicoes', '0003_edicao_apenas_uma_edicao_ativa'),
        ('referenciais', '0004_bncc_por_etapa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['status'], name='curso_status_idx'),
        ),
    ]
