# Generated by Django 5.2.17 on 2026-09-04 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_curso_curso_status_idx'),
        ('edicoes', '0003_edicao_apenas_uma_edicao_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='edicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='edicoes.edicao', verbose_name='edição'),
        ),
    ]
