# Generated by Django 5.2.17 on 2026-08-25 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('sigla', models.CharField(max_length=20, unique=True, verbose_name='sigla')),
                ('descricao', models.TextField(blank=True, verbose_name='descricao')),
                ('min_competencias', models.PositiveSmallIntegerField(default=1, verbose_name='minimo de competencias')),
                ('max_competencias', models.PositiveSmallIntegerField(default=5, verbose_name='maximo de competencias')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'referencial',
                'verbose_name_plural': 'referenciais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('referencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='referenciais.referencial', verbose_name='referencial')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['referencial', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='codigo')),
                ('descricao', models.TextField(verbose_name='descricao')),
                ('etapa', models.CharField(choices=[('EI', 'Educacao Infantil'), ('EF01', '1o ano do Ensino Fundamental'), ('EF02', '2o ano do Ensino Fundamental'), ('EF03', '3o ano do Ensino Fundamental'), ('EF04', '4o ano do Ensino Fundamental'), ('EF05', '5o ano do Ensino Fundamental'), ('EF06', '6o ano do Ensino Fundamental'), ('EF07', '7o ano do Ensino Fundamental'), ('EF08', '8o ano do Ensino Fundamental'), ('EF09', '9o ano do Ensino Fundamental'), ('EM01', '1o ano do Ensino Medio'), ('EM02', '2o ano do Ensino Medio'), ('EM03', '3o ano do Ensino Medio')], max_length=4, verbose_name='etapa')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencias', to='referenciais.categoria', verbose_name='categoria')),
                ('referencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='referenciais.referencial', verbose_name='referencial')),
            ],
            options={
                'verbose_name': 'competencia',
                'verbose_name_plural': 'competencias',
                'ordering': ['referencial', 'etapa', 'ordem', 'codigo'],
                'constraints': [models.UniqueConstraint(fields=('referencial', 'codigo'), name='competencia_unica_no_referencial')],
            },
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('referencial', 'nome'), name='categoria_unica_no_referencial'),
        ),
    ]
