# Generated by Django 5.2.17 on 2026-08-26 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referenciais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='referenciais.categoria', verbose_name='categoria'),
        ),
    ]
