# Generated by Django 5.2.17 on 2026-08-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referenciais', '0002_alter_competencia_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencia',
            options={'ordering': ['referencial', 'etapa', 'ordem', 'codigo'], 'verbose_name': 'competência', 'verbose_name_plural': 'competências'},
        ),
        migrations.AlterField(
            model_name='competencia',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='descricao',
            field=models.TextField(verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='etapa',
            field=models.CharField(choices=[('EI', 'Educação Infantil'), ('EF01', '1º ano do Ensino Fundamental'), ('EF02', '2º ano do Ensino Fundamental'), ('EF03', '3º ano do Ensino Fundamental'), ('EF04', '4º ano do Ensino Fundamental'), ('EF05', '5º ano do Ensino Fundamental'), ('EF06', '6º ano do Ensino Fundamental'), ('EF07', '7º ano do Ensino Fundamental'), ('EF08', '8º ano do Ensino Fundamental'), ('EF09', '9º ano do Ensino Fundamental'), ('EM01', '1º ano do Ensino Médio'), ('EM02', '2º ano do Ensino Médio'), ('EM03', '3º ano do Ensino Médio')], max_length=4, verbose_name='etapa'),
        ),
        migrations.AlterField(
            model_name='referencial',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='referencial',
            name='max_competencias',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='máximo de competências'),
        ),
        migrations.AlterField(
            model_name='referencial',
            name='min_competencias',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='mínimo de competências'),
        ),
    ]
