# Generated by Django 5.2.17 on 2026-08-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referenciais', '0003_alter_competencia_options_alter_competencia_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='objeto_conhecimento',
            field=models.CharField(blank=True, max_length=120, verbose_name='objeto de conhecimento'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='etapa',
            field=models.CharField(choices=[('EI', 'Educação Infantil'), ('EF01', '1º ano do Ensino Fundamental'), ('EF02', '2º ano do Ensino Fundamental'), ('EF03', '3º ano do Ensino Fundamental'), ('EF04', '4º ano do Ensino Fundamental'), ('EF05', '5º ano do Ensino Fundamental'), ('EF06', '6º ano do Ensino Fundamental'), ('EF07', '7º ano do Ensino Fundamental'), ('EF08', '8º ano do Ensino Fundamental'), ('EF09', '9º ano do Ensino Fundamental'), ('EM', 'Ensino Médio')], max_length=4, verbose_name='etapa'),
        ),
    ]
